import { db } from "./db";
import { hackathons, problemStatements } from "@shared/schema";

const seedHackathons = [
  {
    title: "Smart India Hackathon 2025",
    slug: "smart-india-hackathon-2025",
    description: "India's largest open innovation model providing students a platform to solve pressing problems faced by our country. Join 50,000+ students from across India to build solutions for ministries and PSUs.",
    shortDescription: "National-level hackathon for students across India",
    bannerImageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=60",
    organizerName: "Ministry of Education",
    organizerType: "government",
    category: "Open Innovation",
    mode: "hybrid",
    venue: "Multiple Centers",
    city: "Pan India",
    country: "India",
    level: "national",
    prizePool: 5000000,
    currency: "INR",
    maxTeamSize: 6,
    minTeamSize: 4,
    maxParticipants: 50000,
    registrationStartDate: new Date("2024-12-01"),
    registrationEndDate: new Date("2025-01-15"),
    hackathonStartDate: new Date("2025-02-20"),
    hackathonEndDate: new Date("2025-02-22"),
    submissionDeadline: new Date("2025-02-22"),
    judgingStartDate: new Date("2025-02-23"),
    judgingEndDate: new Date("2025-02-25"),
    resultsDate: new Date("2025-02-28"),
    status: "registration_open",
    isPaid: false,
    entryFee: 0,
    eligibility: "Indian students enrolled in recognized institutions",
    tags: ["innovation", "government", "national"],
    isPublished: true,
    isFeatured: true,
  },
  {
    title: "TechnoVerse AI Challenge",
    slug: "technoverse-ai-challenge",
    description: "Premier AI/ML hackathon focused on solving real-world problems using artificial intelligence. Work on cutting-edge machine learning projects and compete for substantial prizes.",
    shortDescription: "Build AI solutions for industry challenges",
    bannerImageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=60",
    organizerName: "IIT Delhi",
    organizerType: "university",
    category: "AI/ML",
    mode: "online",
    city: "Online",
    country: "India",
    level: "national",
    prizePool: 1500000,
    currency: "INR",
    maxTeamSize: 4,
    minTeamSize: 2,
    maxParticipants: 15000,
    registrationStartDate: new Date("2024-12-15"),
    registrationEndDate: new Date("2025-01-20"),
    hackathonStartDate: new Date("2025-02-01"),
    hackathonEndDate: new Date("2025-02-03"),
    submissionDeadline: new Date("2025-02-03"),
    resultsDate: new Date("2025-02-10"),
    status: "registration_open",
    isPaid: false,
    entryFee: 0,
    tags: ["ai", "ml", "deep-learning"],
    isPublished: true,
    isFeatured: true,
  },
  {
    title: "FinTech Innovation Sprint",
    slug: "fintech-innovation-sprint",
    description: "Create next-generation financial solutions with India's leading banks. Build payment systems, lending platforms, or personal finance tools.",
    shortDescription: "Build the future of finance",
    bannerImageUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=60",
    organizerName: "HDFC Bank",
    organizerType: "corporate",
    category: "FinTech",
    mode: "hybrid",
    venue: "HDFC House",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    level: "corporate",
    prizePool: 2000000,
    currency: "INR",
    maxTeamSize: 4,
    minTeamSize: 2,
    maxParticipants: 10000,
    registrationStartDate: new Date("2025-01-01"),
    registrationEndDate: new Date("2025-02-01"),
    hackathonStartDate: new Date("2025-02-15"),
    hackathonEndDate: new Date("2025-02-16"),
    submissionDeadline: new Date("2025-02-16"),
    resultsDate: new Date("2025-02-20"),
    status: "upcoming",
    isPaid: false,
    entryFee: 0,
    tags: ["fintech", "banking", "payments"],
    isPublished: true,
    isFeatured: false,
  },
  {
    title: "GreenTech Sustainable Solutions",
    slug: "greentech-sustainable-solutions",
    description: "Develop sustainable technology solutions for environmental challenges. Focus on renewable energy, waste management, and carbon footprint reduction.",
    shortDescription: "Technology for a greener tomorrow",
    bannerImageUrl: "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800&auto=format&fit=crop&q=60",
    organizerName: "Tata Trust",
    organizerType: "corporate",
    category: "CleanTech",
    mode: "online",
    city: "Online",
    country: "India",
    level: "national",
    prizePool: 1000000,
    currency: "INR",
    maxTeamSize: 5,
    minTeamSize: 2,
    maxParticipants: 8000,
    registrationStartDate: new Date("2025-01-10"),
    registrationEndDate: new Date("2025-02-10"),
    hackathonStartDate: new Date("2025-02-25"),
    hackathonEndDate: new Date("2025-02-27"),
    submissionDeadline: new Date("2025-02-27"),
    resultsDate: new Date("2025-03-05"),
    status: "upcoming",
    isPaid: false,
    entryFee: 0,
    tags: ["sustainability", "cleantech", "environment"],
    isPublished: true,
    isFeatured: false,
  },
  {
    title: "HealthTech Revolution",
    slug: "healthtech-revolution",
    description: "Transform healthcare delivery with innovative technology solutions. Build telemedicine platforms, diagnostic tools, or health monitoring systems.",
    shortDescription: "Building the future of healthcare",
    bannerImageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=60",
    organizerName: "AIIMS Delhi",
    organizerType: "government",
    category: "HealthTech",
    mode: "hybrid",
    venue: "AIIMS Campus",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    level: "national",
    prizePool: 1800000,
    currency: "INR",
    maxTeamSize: 5,
    minTeamSize: 3,
    maxParticipants: 12000,
    registrationStartDate: new Date("2025-01-05"),
    registrationEndDate: new Date("2025-02-05"),
    hackathonStartDate: new Date("2025-03-01"),
    hackathonEndDate: new Date("2025-03-03"),
    submissionDeadline: new Date("2025-03-03"),
    resultsDate: new Date("2025-03-10"),
    status: "registration_open",
    isPaid: false,
    entryFee: 0,
    tags: ["health", "medical", "telemedicine"],
    isPublished: true,
    isFeatured: false,
  },
  {
    title: "Web3 Builders Hackathon",
    slug: "web3-builders-hackathon",
    description: "Build decentralized applications on blockchain technology. Create DeFi protocols, NFT marketplaces, or DAOs.",
    shortDescription: "Decentralize everything",
    bannerImageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=60",
    organizerName: "Polygon Labs",
    organizerType: "corporate",
    category: "Web3",
    mode: "online",
    city: "Online",
    country: "India",
    level: "national",
    prizePool: 2500000,
    currency: "INR",
    maxTeamSize: 4,
    minTeamSize: 1,
    maxParticipants: 10000,
    registrationStartDate: new Date("2025-01-15"),
    registrationEndDate: new Date("2025-02-15"),
    hackathonStartDate: new Date("2025-03-10"),
    hackathonEndDate: new Date("2025-03-12"),
    submissionDeadline: new Date("2025-03-12"),
    resultsDate: new Date("2025-03-20"),
    status: "upcoming",
    isPaid: false,
    entryFee: 0,
    tags: ["blockchain", "web3", "defi"],
    isPublished: true,
    isFeatured: false,
  },
];

async function seed() {
  console.log("Seeding hackathons...");
  
  for (const hackathon of seedHackathons) {
    try {
      await db.insert(hackathons).values(hackathon as any).onConflictDoNothing();
      console.log(`  Created: ${hackathon.title}`);
    } catch (error: any) {
      if (error.code === "23505") {
        console.log(`  Skipped (exists): ${hackathon.title}`);
      } else {
        console.error(`  Error creating ${hackathon.title}:`, error.message);
      }
    }
  }
  
  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
